### ISSUE TITLE
Sony Xperia XZ1 PixelExperienceP-a64-aonly February build stuck on boot logo

### ISSUE THREAD

**Issue by duffman128** [EnesSastim/Downloads#23]
No logs available. PixelExperienceP-a64-aonly 2019/02/09 build doesn't boot up even after clean install and Magisk installation on Sony Xperia XZ1.

**Comment by rocknonstop** [comment]
Not sure

**Comment by duffman128** [comment]
I'll wait for the next build.

**Comment by duffman128** [comment]
Btw, the size of the image is 200MB smaller that the 2019/01/11 image. It's almost as if this image is for the 32bit a-only version instead of 64bit a-only.

**Comment by duffman128** [comment]
**Facepalm** seems like I downloaded the wrong image.
