### ISSUE TITLE
Bluetooth headphone can't used

### ISSUE THREAD

**Issue by zcl0621** [EnesSastim/Downloads#6]
the 2018-11-08 ab buid bluetooth headphone can't listen music and call.
Previous version can be listen music but can't used call.
My device Lenovo Z5

**Comment by zcl0621** [comment]
update.
bluetooth can‘t listen music. but can be call.
bluetooth headphone is sony wi1000x.
And my other friend also can't use bluetooth headphone to listen music.

**Comment by WuSiYu** [comment]
same issue on xiaomi mix2s

**Comment by rodrigoclp** [comment]
On XDA forum has a .zip file to use with magisk. This file fix the problem.

**Comment by AlonsoK28** [comment]
> On XDA forum has a .zip file to use with magisk. This file fix the problem.
> [magisk-Fix-Bluetooth_Audio-Pie-z5-3.0.zip](https://github.com/EnesSastim/Downloads/files/3039346/magisk-Fix-Bluetooth_Audio-Pie-z5-3.0.zip)

I have already flashed the zip with Magisk and fixes the problem for the bluetooth call audio (calls in the phone app), **but it does not correct the media audio (spotify, apple music, games, youtube ...)**

Is there anything else I can do?

**Comment by rodrigoclp** [comment]
There is another rom based on pixel experience and it is no have any bug on
bluetooth or another any bug knowed.

!_NkZ3ct8dFdzc4zpF_ZOTB_O_Dvl3eXMfZFX1N77L5s

Em dom, 14 de abr de 2019 01:44, AlonsoKyoyama <notifications@github.com>
escreveu:

**Comment by AlonsoK28** [comment]
> There is another rom based on pixel experience and it is no have any bug on bluetooth or another any bug knowed. !_NkZ3ct8dFdzc4zpF_ZOTB_O_Dvl3eXMfZFX1N77L5s Em dom, 14 de abr de 2019 01:44, 

 @rodrigoclp Thank you very much for your time and your response

Could you give me some way to find that other ROM?

Is it possible to share the link?

I'm going to install it in a XIAOMI MI 8 SE

**Comment by rodrigoclp** [comment]
Github remove link. Try this on mega:
m_e_g_a_._n_z/#!_NkZ3ct8dFdzc4zpF_ZOTB_O_Dvl3eXMfZFX1N77L5s

Remove _


Em dom, 14 de abr de 2019 15:28, AlonsoKyoyama <notifications@github.com>
escreveu:

**Comment by rodrigoclp** [comment]
h t t p s://mega.nz/#!B5JQRaoC!_NkZ3ct8dFdzc4zpF_ZOTB_O_Dvl3eXMfZFX1N77L5s

Em dom, 14 de abr de 2019 15:36, Rodrigo Pádua <rodrigoclp@gmail.com>
escreveu:
